name: Build and Deploy Lambda Function

on:
  workflow_dispatch:
    inputs:
      Action:
        description: Terraform Action to be performed
        type: choice
        required: true
        options:
        - Plan
        - Apply
        - Destroy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Specify the Go version

      - name: Initialize Go modules
        run: go mod init mylambda

      - name: Install AWS Lambda Go SDK dependencies
        run: |
          go get github.com/aws/aws-lambda-go/lambda
          go get github.com/aws/aws-lambda-go/events

      - name: Build the Go Lambda function
        run: GOOS=linux GOARCH=amd64 go build -o main main.go

      - name: Package the Lambda function
        run: zip lambda-package.zip main

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-artifact
          path: lambda-package.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deploying

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: lambda-artifact

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
        run: echo -e "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\nregion = $AWS_DEFAULT_REGION" > ~/.aws/credentials

      - name: Upload code to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp lambda-package.zip s3://test-bucket-ashvini/

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name my-go-lambda \
            --s3-bucket your-bucket-name \
            --s3-key lambda-package.zip

  deploy-tf:
    runs-on: ubuntu-latest
    needs: deploy 
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform
  
      - name: Apply Terraform configuration
        if: ${{ github.event.inputs.Action == 'Plan' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:  terraform plan 
        working-directory: ./terraform
  
      - name: Apply Terraform configuration
        if: ${{ github.event.inputs.Action == 'Apply' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve
        working-directory: ./terraform
  
      - name: Destroy Terraform configuration
        if: ${{ github.event.inputs.Action == 'Destroy' }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform destroy -auto-approve  
        working-directory: ./terraform                     